# Generated by Django 3.2.8 on 2021-10-12 21:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advogados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=30)),
                ('classe', models.CharField(max_length=100)),
                ('diligencia', models.TextField()),
                ('prioridade', models.BooleanField(default=False)),
                ('data_diligencia', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advogados.advogado')),
            ],
        ),
    ]
