# Generated by Django 3.2.8 on 2021-10-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diligencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diligencia',
            name='tipo',
            field=models.CharField(default='Despacho', max_length=100),
        ),
    ]
